//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAula16082021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int QtdAlunos { get; set; }
        public string NomeProfessor { get; set; }
    }
}
