//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evento
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Evento
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
        public int QtdPessoas { get; set; }
        public int QtdMaxPermitida { get; set; }
        public decimal ValorPorPessoa { get; set; }
    }
}
